name: Build and Test

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build (skip npm install)
        run: echo "Running build process for learning"

